# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicator" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "ea3278e2189326de65d79cfd4da9ff42fd91530a138cb9863eadc1c184eda569"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db3f96fcd316e33fc8b0b4f6805ee07313f5338fa13c46889fc8473d7a5f9852"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d35cf51192f4bc3eb92d32c2a63304fdbc561243a2bb8e406d0a5c7f9d1a83f1"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "replicator"
  desc "Multi-agent coordination for AI coding agents"
  homepage "https://github.com/unbound-force/replicator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicator"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/replicator"]
    end
  end

  # No zap stanza required

end
