package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/unbound-force/replicator/internal/db"
	"github.com/unbound-force/replicator/internal/memory"
	commstools "github.com/unbound-force/replicator/internal/tools/comms"
	forgetools "github.com/unbound-force/replicator/internal/tools/forge"
	memorytools "github.com/unbound-force/replicator/internal/tools/memory"
	"github.com/unbound-force/replicator/internal/tools/org"
	"github.com/unbound-force/replicator/internal/tools/registry"
)

func docsCmd() *cobra.Command {
	var outputFlag string
	cmd := &cobra.Command{
		Use:   "docs",
		Short: "Generate MCP tool reference documentation",
		Long: `Generates a markdown document listing all registered MCP tools
with their names, descriptions, and argument schemas.

Output is grouped by category: Org, Comms, Forge, Memory.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDocs(outputFlag)
		},
	}
	cmd.Flags().StringVar(&outputFlag, "output", "", "Write to file instead of stdout")
	return cmd
}

// runDocs generates the tool reference markdown.
func runDocs(outputPath string) error {
	// Build the full registry (same wiring as serve.go).
	store, err := db.OpenMemory()
	if err != nil {
		return fmt.Errorf("open memory db: %w", err)
	}
	defer store.Close()

	reg := registry.New()
	org.Register(reg, store)
	commstools.Register(reg, store)
	forgetools.Register(reg, store)
	memClient := memory.NewClient("http://localhost:3333/mcp/")
	memorytools.Register(reg, memClient)

	var w io.Writer = os.Stdout
	if outputPath != "" {
		f, err := os.Create(outputPath)
		if err != nil {
			return fmt.Errorf("create output file: %w", err)
		}
		defer f.Close()
		w = f
	}

	return writeDocs(w, reg)
}

// category maps tool name prefixes to display categories.
var categories = []struct {
	prefix string
	name   string
}{
	{"org_", "Org"},
	{"comms_", "Comms"},
	{"forge_", "Forge"},
	{"hivemind_", "Memory"},
}

func toolCategory(name string) string {
	for _, c := range categories {
		if strings.HasPrefix(name, c.prefix) {
			return c.name
		}
	}
	return "Other"
}

func writeDocs(w io.Writer, reg *registry.Registry) error {
	fmt.Fprintf(w, "# MCP Tool Reference\n\n")
	fmt.Fprintf(w, "Auto-generated by `replicator docs`. %d tools registered.\n\n", reg.Count())

	// Group tools by category.
	grouped := make(map[string][]*registry.Tool)
	for _, t := range reg.List() {
		cat := toolCategory(t.Name)
		grouped[cat] = append(grouped[cat], t)
	}

	// Write in category order.
	for _, c := range categories {
		tools := grouped[c.name]
		if len(tools) == 0 {
			continue
		}

		// Sort tools within category alphabetically.
		sort.Slice(tools, func(i, j int) bool {
			return tools[i].Name < tools[j].Name
		})

		fmt.Fprintf(w, "## %s (%d tools)\n\n", c.name, len(tools))

		for _, t := range tools {
			fmt.Fprintf(w, "### `%s`\n\n", t.Name)
			fmt.Fprintf(w, "%s\n\n", t.Description)

			// Pretty-print the input schema.
			var schema any
			if err := json.Unmarshal(t.InputSchema, &schema); err == nil {
				pretty, _ := json.MarshalIndent(schema, "", "  ")
				fmt.Fprintf(w, "```json\n%s\n```\n\n", pretty)
			}
		}
	}

	// Write any uncategorized tools.
	if other, ok := grouped["Other"]; ok && len(other) > 0 {
		fmt.Fprintf(w, "## Other (%d tools)\n\n", len(other))
		for _, t := range other {
			fmt.Fprintf(w, "### `%s`\n\n%s\n\n", t.Name, t.Description)
		}
	}

	return nil
}
